from metro_sim.player.models.crew_member_state import CrewMemberState


def create_initial_crew_members(
    location_id: str = "paveletskaya",
) -> list[CrewMemberState]:
    return [
        CrewMemberState(
            id="crew_001",
            name="Mikhail",
            role="stalker",
            health=82,
            morale=58,
            fatigue=10,
            skills={
                "scouting": 45,
                "combat": 35,
                "survival": 40,
                "technical": 10,
                "medical": 5,
                "trade": 10,
            },
            traits=["tunnel_runner"],
            current_location_id=location_id,
        ),
        CrewMemberState(
            id="crew_002",
            name="Anya",
            role="medic",
            health=76,
            morale=64,
            fatigue=8,
            skills={
                "scouting": 15,
                "combat": 10,
                "survival": 25,
                "technical": 15,
                "medical": 55,
                "trade": 20,
            },
            traits=["steady_hands"],
            current_location_id=location_id,
        ),
        CrewMemberState(
            id="crew_003",
            name="Boris",
            role="guard",
            health=88,
            morale=52,
            fatigue=12,
            skills={
                "scouting": 20,
                "combat": 55,
                "survival": 35,
                "technical": 10,
                "medical": 5,
                "trade": 5,
            },
            traits=["disciplined"],
            current_location_id=location_id,
        ),
        CrewMemberState(
            id="crew_004",
            name="Irina",
            role="technician",
            health=70,
            morale=60,
            fatigue=9,
            skills={
                "scouting": 10,
                "combat": 8,
                "survival": 20,
                "technical": 60,
                "medical": 15,
                "trade": 15,
            },
            traits=["field_engineer"],
            current_location_id=location_id,
        ),
        CrewMemberState(
            id="crew_005",
            name="Nikolai",
            role="trader",
            health=74,
            morale=62,
            fatigue=7,
            skills={
                "scouting": 18,
                "combat": 12,
                "survival": 25,
                "technical": 10,
                "medical": 8,
                "trade": 60,
            },
            traits=["silver_tongue"],
            current_location_id=location_id,
        ),
        CrewMemberState(
            id="crew_006",
            name="Sasha",
            role="runner",
            health=80,
            morale=55,
            fatigue=6,
            skills={
                "scouting": 40,
                "combat": 25,
                "survival": 45,
                "technical": 8,
                "medical": 5,
                "trade": 10,
            },
            traits=["fast_learner"],
            current_location_id=location_id,
        ),
    ]